{
  "ProfileID": "d4d07bb8-9592-4a9b-a75d-656b7bf50f5a",
  "ProfileName": "Dark&Light-Server1",
  "InstallDirectory": "D:\\Program Files (x86)\\Steam\\steamapps\\common\\Dark and Light Server Manager\\Servers\\DnLServer1",
  "LastInstalledVersion": "100.32247",
  "ServerName": "Lorpian Planet",
  "ServerPassword": "fawkd",
  "AdminPassword": "FAWKD",
  "SpectatorPassword": "watch",
  "ServerPort": 7777,
  "QueryPort": 27015,
  "ServerIP": "192.168.0.18",
  "UseRawSockets": true,
  "EnableBanListURL": false,
  "BanListURL": "",
  "MaxPlayers": 15,
  "EnableKickIdlePlayers": true,
  "KickIdlePlayersPeriod": 2400,
  "RCONEnabled": false,
  "RCONPort": 32330,
  "RCONServerGameLogBuffer": 600,
  "AdminLogging": false,
  "ServerMap": "/Game/DNL/Maps/CapeOfSacredPath/DNL_ALL",
  "TotalConversionModId": "",
  "ServerModIds": "",
  "EnableExtinctionEvent": false,
  "AutoSavePeriodMinutes": 5.0,
  "MOTD": "",
  "MOTDDuration": 5,
  "MOTDIntervalEnabled": false,
  "MOTDInterval": 60,
  "DisableValveAntiCheatSystem": true,
  "DisablePlayerMovePhysicsOptimization": false,
  "DisableAntiSpeedHackDetection": true,
  "SpeedHackBias": 0.0,
  "UseBattlEye": false,
  "ForceRespawnDinos": false,
  "EnableServerAdminLogs": false,
  "ServerAdminLogsIncludeTribeLogs": false,
  "ServerRCONOutputTribeLogs": false,
  "NotifyAdminCommandsInChat": false,
  "MaxTribeLogs": 100,
  "TribeLogDestroyedEnemyStructures": false,
  "ForceDirectX10": false,
  "ForceShaderModel4": false,
  "ForceLowMemory": false,
  "ForceNoManSky": false,
  "UseAllAvailableCores": true,
  "UseCache": false,
  "AltSaveDirectoryName": "",
  "EnableWebAlarm": false,
  "WebAlarmKey": "",
  "WebAlarmUrl": "",
  "UseNoMemoryBias": false,
  "StasisKeepControllers": false,
  "CrossServerClusterId": "",
  "ClusterDirOverride": false,
  "BranchName": "",
  "BranchPassword": "",
  "ProcessPriority": "normal",
  "ProcessAffinity": 0,
  "AdditionalArgs": "",
  "LauncherArgsOverride": false,
  "LauncherArgs": "",
  "EnableAutoBackup": false,
  "EnableAutoStart": false,
  "EnableAutoUpdate": false,
  "EnableAutoShutdown1": false,
  "AutoShutdownTime1": "00:00",
  "ShutdownDaysOfTheWeek1": 127,
  "RestartAfterShutdown1": true,
  "UpdateAfterShutdown1": false,
  "EnableAutoShutdown2": false,
  "AutoShutdownTime2": "00:00",
  "ShutdownDaysOfTheWeek2": 127,
  "RestartAfterShutdown2": true,
  "UpdateAfterShutdown2": false,
  "AutoRestartIfShutdown": false,
  "EnableHardcore": false,
  "EnablePVP": true,
  "AllowCaveBuildingPvE": true,
  "DisableFriendlyFirePvP": true,
  "DisableFriendlyFirePvE": true,
  "DisableLootCrates": false,
  "AllowCrateSpawnsOnTopOfStructures": true,
  "EnableExtraStructurePreventionVolumes": false,
  "DifficultyOffset": 2.428571,
  "MaxNumberOfPlayersInTribe": 0,
  "EnableTributeDownloads": false,
  "PreventDownloadSurvivors": true,
  "PreventDownloadItems": true,
  "PreventDownloadDinos": true,
  "PreventUploadSurvivors": true,
  "PreventUploadItems": true,
  "PreventUploadDinos": true,
  "NoTransferFromFiltering": false,
  "OverrideTributeCharacterExpirationSeconds": false,
  "OverrideTributeItemExpirationSeconds": false,
  "OverrideTributeDinoExpirationSeconds": false,
  "OverrideMinimumDinoReuploadInterval": false,
  "TributeCharacterExpirationSeconds": 86400,
  "TributeItemExpirationSeconds": 86400,
  "TributeDinoExpirationSeconds": 86400,
  "MinimumDinoReuploadInterval": 43200,
  "IncreasePvPRespawnInterval": false,
  "IncreasePvPRespawnIntervalCheckPeriod": 300,
  "IncreasePvPRespawnIntervalMultiplier": 1.0,
  "IncreasePvPRespawnIntervalBaseAmount": 60,
  "PreventOfflinePvP": true,
  "PreventOfflinePvPInterval": 30,
  "AutoPvETimer": false,
  "AutoPvEUseSystemTime": false,
  "AutoPvEStartTimeSeconds": 0,
  "AutoPvEStopTimeSeconds": 0,
  "AllowTribeWarPvE": false,
  "AllowTribeWarCancelPvE": true,
  "AllowTribeAlliances": true,
  "AllowCustomRecipes": true,
  "CustomRecipeEffectivenessMultiplier": 2.0,
  "CustomRecipeSkillMultiplier": 5.0,
  "EnableDiseases": false,
  "NonPermanentDiseases": false,
  "OverrideNPCNetworkStasisRangeScale": false,
  "NPCNetworkStasisRangeScalePlayerCountStart": 70,
  "NPCNetworkStasisRangeScalePlayerCountEnd": 120,
  "NPCNetworkStasisRangeScalePercentEnd": 0.5,
  "UseCorpseLocator": true,
  "PreventSpawnAnimations": true,
  "AllowUnlimitedRespecs": true,
  "AllowPlatformSaddleMultiFloors": true,
  "OxygenSwimSpeedStatMultiplier": 3.0,
  "SupplyCrateLootQualityMultiplier": 100.0,
  "FishingLootQualityMultiplier": 25.0,
  "EnableNoFishLoot": true,
  "EnableGlobalVoiceChat": false,
  "EnableProximityChat": false,
  "EnablePlayerLeaveNotifications": true,
  "EnablePlayerJoinedNotifications": true,
  "AllowCrosshair": true,
  "AllowHUD": true,
  "AllowThirdPersonView": false,
  "AllowMapPlayerLocation": true,
  "AllowPVPGamma": false,
  "AllowPvEGamma": false,
  "ShowFloatingDamageText": true,
  "AllowHitMarkers": false,
  "EnableFlyerCarry": true,
  "XPMultiplier": 1.0,
  "OverrideMaxExperiencePointsPlayer": 1000000,
  "PlayerDamageMultiplier": 1.0,
  "PlayerResistanceMultiplier": 1.0,
  "PlayerCharacterWaterDrainMultiplier": 1.0,
  "PlayerCharacterFoodDrainMultiplier": 1.0,
  "PlayerCharacterStaminaDrainMultiplier": 1.0,
  "PlayerCharacterHealthRecoveryMultiplier": 1.25,
  "PlayerHarvestingDamageMultiplier": 1.2,
  "CraftingSkillBonusMultiplier": 2.0,
  "OverrideMaxExperiencePointsDino": 1000000,
  "DinoDamageMultiplier": 1.0,
  "TamedDinoDamageMultiplier": 1.0,
  "DinoResistanceMultiplier": 1.0,
  "TamedDinoResistanceMultiplier": 1.0,
  "MaxTamedDinos": 4000,
  "DinoCharacterFoodDrainMultiplier": 1.0,
  "DinoCharacterStaminaDrainMultiplier": 0.8,
  "DinoCharacterHealthRecoveryMultiplier": 1.0,
  "DinoCountMultiplier": 1.05,
  "DinoHarvestingDamageMultiplier": 3.0,
  "DinoTurretDamageMultiplier": 5.0,
  "AllowRaidDinoFeeding": false,
  "RaidDinoCharacterFoodDrainMultiplier": 1.0,
  "EnableAllowCaveFlyers": true,
  "AllowFlyingStaminaRecovery": true,
  "PreventMateBoost": false,
  "DisableDinoDecayPvE": false,
  "DisableDinoDecayPvP": true,
  "AutoDestroyDecayedDinos": true,
  "PvEDinoDecayPeriodMultiplier": 1.0,
  "ForceFlyerExplosives": false,
  "AllowMultipleAttachedC4": false,
  "DisableDinoRiding": false,
  "DisableDinoTaming": false,
  "MaxPersonalTamedDinos": 500.0,
  "MatingIntervalMultiplier": 1.0,
  "EggHatchSpeedMultiplier": 1.0,
  "BabyMatureSpeedMultiplier": 1.0,
  "BabyFoodConsumptionSpeedMultiplier": 1.0,
  "DisableImprintDinoBuff": false,
  "AllowAnyoneBabyImprintCuddle": false,
  "BabyImprintingStatScaleMultiplier": 1.0,
  "BabyCuddleIntervalMultiplier": 1.0,
  "BabyCuddleGracePeriodMultiplier": 1.0,
  "BabyCuddleLoseImprintQualitySpeedMultiplier": 1.0,
  "TamingSpeedMultiplier": 1.0,
  "HarvestAmountMultiplier": 1.055,
  "ResourcesRespawnPeriodMultiplier": 0.225,
  "ResourceNoReplenishRadiusPlayers": 0.05,
  "ResourceNoReplenishRadiusStructures": 0.45,
  "HarvestHealthMultiplier": 2.5,
  "UseOptimizedHarvestingHealth": true,
  "ClampResourceHarvestDamage": true,
  "ClampItemSpoilingTimes": false,
  "DayCycleSpeedScale": 0.5,
  "DayTimeSpeedScale": 0.5,
  "NightTimeSpeedScale": 10.0,
  "GlobalSpoilingTimeMultiplier": 18500.0,
  "GlobalItemDecompositionTimeMultiplier": 1.0,
  "GlobalCorpseDecompositionTimeMultiplier": 1.5,
  "CropDecaySpeedMultiplier": 0.005,
  "CropGrowthSpeedMultiplier": 100.0,
  "LayEggIntervalMultiplier": 0.0,
  "PoopIntervalMultiplier": 0.0,
  "HairGrowthSpeedMultiplier": 0.0,
  "CraftXPMultiplier": 1.0,
  "GenericXPMultiplier": 1.0,
  "HarvestXPMultiplier": 1.0,
  "KillXPMultiplier": 1.0,
  "SpecialXPMultiplier": 5.0,
  "StructureResistanceMultiplier": 1.0,
  "StructureDamageMultiplier": 3.0,
  "StructureDamageRepairCooldown": 0,
  "PvPStructureDecay": false,
  "PvPZoneStructureDamageMultiplier": 2.0,
  "MaxStructuresVisible": 5000.0,
  "PerPlatformMaxStructuresMultiplier": 1.0,
  "MaxPlatformSaddleStructureLimit": 50,
  "OverrideStructurePlatformPrevention": true,
  "FlyerPlatformAllowUnalignedDinoBasing": true,
  "PvEAllowStructuresAtSupplyDrops": true,
  "EnableStructureDecayPvE": false,
  "PvEStructureDecayDestructionPeriod": 0.0,
  "PvEStructureDecayPeriodMultiplier": 1.0,
  "AutoDestroyOldStructuresMultiplier": 5.0,
  "ForceAllStructureLocking": true,
  "PassiveDefensesDamageRiderlessDinos": true,
  "EnableAutoDestroyStructures": true,
  "OnlyAutoDestroyCoreStructures": false,
  "OnlyDecayUnsnappedCoreStructures": true,
  "FastDecayUnsnappedCoreStructures": true,
  "DestroyUnconnectedWaterPipes": true,
  "DisableStructurePlacementCollision": true,
  "EnableFastDecayInterval": true,
  "FastDecayInterval": 3600,
  "OnlyAllowSpecifiedEngrams": false,
  "ServerFilesAdmins": [
    {
      "SteamId": "76561198034156887",
      "SteamName": "Emlorp"
    },
    {
      "SteamId": "76561198041305354",
      "SteamName": "Zerolorp"
    },
    {
      "SteamId": "76561198179053549",
      "SteamName": "ForgottenSoul"
    },
    {
      "SteamId": "76561198133037250",
      "SteamName": "Marshmallowsam"
    },
    {
      "SteamId": "76561198112356464",
      "SteamName": "Door-to-Door Hentai Salesman"
    },
    {
      "SteamId": "76561198052848328",
      "SteamName": "Kingprawn"
    },
    {
      "SteamId": "76561198042233120",
      "SteamName": "HunterX"
    },
    {
      "SteamId": "76561198072095186",
      "SteamName": "TheNomBomb"
    },
    {
      "SteamId": "76561198077534201",
      "SteamName": "Zeffy"
    }
  ],
  "EnableExclusiveJoin": true,
  "ServerFilesExclusive": [
    {
      "SteamId": "76561198034156887",
      "SteamName": "Emlorp"
    },
    {
      "SteamId": "76561198041305354",
      "SteamName": "Zerolorp"
    },
    {
      "SteamId": "76561198179053549",
      "SteamName": "ForgottenSoul"
    },
    {
      "SteamId": "76561198133037250",
      "SteamName": "Marshmallowsam"
    },
    {
      "SteamId": "76561198112356464",
      "SteamName": "Door-to-Door Hentai Salesman"
    },
    {
      "SteamId": "76561198052848328",
      "SteamName": "Kingprawn"
    },
    {
      "SteamId": "76561198042233120",
      "SteamName": "HunterX"
    },
    {
      "SteamId": "76561198072095186",
      "SteamName": "TheNomBomb"
    },
    {
      "SteamId": "76561198077534201",
      "SteamName": "Zeffy"
    }
  ],
  "ServerFilesWhitelisted": [
    {
      "SteamId": "76561198034156887",
      "SteamName": "Emlorp"
    },
    {
      "SteamId": "76561198041305354",
      "SteamName": "Zerolorp"
    },
    {
      "SteamId": "76561198179053549",
      "SteamName": "ForgottenSoul"
    },
    {
      "SteamId": "76561198133037250",
      "SteamName": "Marshmallowsam"
    },
    {
      "SteamId": "76561198112356464",
      "SteamName": "Door-to-Door Hentai Salesman"
    },
    {
      "SteamId": "76561198052848328",
      "SteamName": "Kingprawn"
    },
    {
      "SteamId": "76561198042233120",
      "SteamName": "HunterX"
    },
    {
      "SteamId": "76561198072095186",
      "SteamName": "TheNomBomb"
    },
    {
      "SteamId": "76561198077534201",
      "SteamName": "Zeffy"
    }
  ],
  "RCONWindowExtents": "0,0,0,0",
  "PlayerListWindowExtents": "1916,555,300,500"
}